name: MLflow CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: 
    contents: write
    
env:
  CSV_URL: "MLproject/train_processed.csv"
  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      #Install mlflow
      - name: Install dependencies
        run: pip install mlflow==2.18.0 scikit-learn pandas optuna matplotlib seaborn

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local 
  
      - name: Debug nunjukkin dimana mlruns dan mlartifact
        run: |
          echo "=== CURRENT DIR ==="
          pwd
          echo "=== ROOT FILES ==="
          ls -la
          echo "=== mlruns location ==="
          find . -name "mlruns" -type d || echo "mlruns not found"
          echo "=== mlartifacts location ==="
          find . -name "mlartifacts" -type d || echo "mlartifacts not found"

      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      #Upload ke github
      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow_full_artifacts_run_${{ env.RUN_ID }}
          path: |
            MLProject/mlruns/
            MLProject/mlartifacts/
          
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri runs:/${{ env.RUN_ID }}/model \
            --name ${{ secrets.DOCKERHUB_USERNAME }}/hilmi-diabetes-model:latest

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKERHUB_USERNAME }}/cc:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cc:latest
